 PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?coordinates WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-luka#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-luka#farm-1> as ?farm)
   <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-luka#LandSection-1> hmas:contains ?Coordinates.
   ?Coordinates td:hasCoordinates ?coordinates
 }
}
